name: clang-format Check
on:
  push:
    paths: 
      - unreal/Puerts/Source/**
      - .clang-format
  pull_request:
    paths: 
      - unreal/Puerts/Source/**
      - .clang-format
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'unreal/Puerts/Source'
            exclude: 'WasmCore/ThirdPart'
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '12'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
